#version: "3.2"
services:
        servidor-orientdb:
                image: orientdb
                ports:
                        - "2424:2424"
                        - "2480:2480" 
                environment:
                        ORIENTDB_ROOT_PASSWORD: "rootpwd"
                
        cliente-js:
                build:
                        context: .
                        dockerfile: Dockerfile
                depends_on:
                        - servidor-orientdb                     
